[build.environment]
    NODE_ENV = "23.5.0"
    NETLIFY_SKIP_PYTHON = "true"
    NETLIFY_SKIP_GO = "true"
    NETLIFY_SKIP_RUBY = "true"


[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://scripts.simpleanalyticscdn.com; connect-src 'self' https://queue.simpleanalyticscdn.com; img-src 'self' https://queue.simpleanalyticscdn.com https://simpleanalyticsbadges.com;"
