[build.environment]
    NODE_ENV = "23.5.0"
    NETLIFY_SKIP_PYTHON = "true"
    NETLIFY_SKIP_GO = "true"
    NETLIFY_SKIP_RUBY = "true"


[[headers]]
  for = "/*"
  [headers.values]
        Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://scripts.simpleanalyticscdn.com https://giscus.app; connect-src 'self' https://queue.simpleanalyticscdn.com https://giscus.app; img-src 'self' data: https://queue.simpleanalyticscdn.com https://simpleanalyticsbadges.com https://swaraj.ing;"
